import React from 'react'

const head = () => {
  return (
    <div>head</div>
  )
}

export default function head({params}) {
    return(
        <>
           <title>{params.movie}</title>
           <meta content="width=device-width, initial-scale=1" name="viewport"/>
           <meta name="description" content="Generated by create next app"/>
           <link rel="icon" href="/favicon.ico" />
        </>
    )

}