import './globals.css'
import Link from 'next/link';
import { Montserrat } from 'next/font/google';



const montserrat = Montserrat({ 
  weight : ['400', '700'], 
  subsets: ['latin'],
  variable: '--font-montserrat',
    
  })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${montserrat.className}`} >
        <nav>
          <h1>Logo</h1>
          <ul>
            <li>
              <a href='#'>About1</a>
            </li>
            <li>
              <a href='#'>Sign Up</a>
            </li>
            <li>
              <a href='#'>Sunscribe Us</a>
            </li>
          </ul>
        </nav>
        
        
        
        {children}
        
      </body>
      
    </html>
  )
}
